SELECT PLAYER_ID FROM T_GUILD_INC_EXP_HISTORY GIE 
WHERE GIE.PLAYER_ID=(
	SELECT PLAYER_ID FROM T_GUILD_PLAYER GP WHERE GP.GUILD_PLAYER_ID=(
		SELECT DISTINCT PLAYER_ID FROM T_GUILD_INC_EXP_HISTORY GIE1 WHERE GP.GUILD_PLAYER_ID=GIE.PLAYER_ID
		)
);

UPDATE T_GUILD_INC_EXP_HISTORY GIE SET GIE.PLAYER_ID=(
	SELECT PLAYER_ID FROM T_GUILD_PLAYER GP WHERE GP.GUILD_PLAYER_ID=(
		SELECT DISTINCT PLAYER_ID FROM T_GUILD_INC_EXP_HISTORY GIE1 WHERE GP.GUILD_PLAYER_ID=GIE1.PLAYER_ID
		)
);

