log4j.rootLogger=INFO, stdout, file

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[%d{MM/dd/ HH:mm:ss}] %c [%p] %x %n[M] %m%n

log4j.appender.file=org.apache.log4j.DailyRollingFileAppender
log4j.appender.file.File=chess.log
log4j.appender.file.DatePattern ='.'MM-dd-yyyy
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=[%d{MM/dd/ HH:mm:ss}] %c [%p] %x %n[M] %m%n

# SqlMap logging configuration...
log4j.logger.Message=INFO,message
log4j.appender.message=org.apache.log4j.DailyRollingFileAppender
log4j.appender.message.File=message.log
log4j.appender.message.DatePattern ='.'MM-dd-yyyy
log4j.appender.message.layout=org.apache.log4j.PatternLayout
log4j.appender.message.layout.ConversionPattern=[%d{MM/dd/ HH:mm:ss}] %c [%p] %x %n[M] %m%n

log4j.logger.Login=INFO,login
log4j.appender.login=org.apache.log4j.DailyRollingFileAppender
log4j.appender.login.File=login.log
log4j.appender.login.DatePattern ='.'MM-dd-yyyy
log4j.appender.login.layout=org.apache.log4j.PatternLayout
log4j.appender.login.layout.ConversionPattern=[%d{MM/dd/ HH:mm:ss}]%m%n

log4j.logger.GoAction=INFO,go
log4j.appender.go=org.apache.log4j.DailyRollingFileAppender
log4j.appender.go.File=register.log
log4j.appender.go.DatePattern ='.'MM-dd-yyyy
log4j.appender.go.layout=org.apache.log4j.PatternLayout
log4j.appender.go.layout.ConversionPattern=[%d{MM/dd/ HH:mm:ss}]%m%n

log4j.logger.DB=INFO,db
log4j.appender.db=org.apache.log4j.DailyRollingFileAppender
log4j.appender.db.File=database.log
log4j.appender.db.DatePattern ='.'MM-dd-yyyy
log4j.appender.db.layout=org.apache.log4j.PatternLayout
log4j.appender.db.layout.ConversionPattern=[%d{MM/dd/ HH:mm:ss}]%m%n

#log4j.logger.java.sql.Connection=DEBUG
#log4j.logger.java.sql.Statement=DEBUG
#log4j.logger.java.sql.PreparedStatement=DEBUG
#log4j.logger.java.sql.ResultSet=DEBUG
